name: wss_chat_server
description: Websocket server chat with rooms, chats, friends and more. Writed on dart
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.0 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  lints: ^1.0.0
dependencies: {freezed: ^2.1.0+1, freezed_annotation: ^2.1.0, intl: ^0.17.0, json_annotation: ^4.6.0, sqlite3: ^1.7.2}
